this is exception handling example 4 with nested try